version: "3.3"
services:
  flask:
    build: ./api
    image: recipe-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/src/src/api.py
    volumes: 
      - ./api:/src
    command: 'poetry run flask run --host=0.0.0.0'
    
  notebook:
    build: ./preprocessing
    image: recipe-api-preprocessing
    ports:
      - "8888:8888"
    volumes: 
      - ./preprocessing:/src
    command: 'poetry run jupyter lab --allow-root --ip 0.0.0.0 --no-browser'
    
  web:
    build: ./web
    image: recipe-web
    ports:
      - "3000:3000"
    volumes: 
      - ./web:/src
    command: 'npm start'
