version: "3.3"
services:
  flask:
    build: ./api
    image: recipe-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/src/api.py
      - DATA_CONFIG_FILE=config.json
      - DATA_ROOT_FOLDER=/data
      - MODEL_KEY=model_2
    volumes: 
      - ./api:/app
      - ./api-data:/data
    command: 'poetry run flask run --host=0.0.0.0'
    
  preprocessing:
    build: ./preprocessing
    image: recipe-api-preprocessing
    ports:
      - "8888:8888"
    volumes: 
      - ./preprocessing:/app
      - ./data:/data
      - ./tmp:/tmp
    command: 'poetry run jupyter lab --allow-root --ip 0.0.0.0 --no-browser'
    
  web:
    build: ./web
    image: recipe-web
    ports:
      - "3000:3000"
    volumes: 
      - ./web:/app
    command: 'npm start'
